# Generated by Django 4.2.7 on 2023-12-27 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
