# Generated by Django 4.2.7 on 2024-01-06 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_notification_delete_notifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('unit', models.CharField(max_length=255)),
                ('assignment', models.CharField(max_length=255)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
