# Generated by Django 4.2.7 on 2024-01-07 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_assignment_assignmentreport_lesson_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentreport',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
