# Generated by Django 4.2.7 on 2024-01-07 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_assignmentreport_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentreport',
            name='score',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=4),
            preserve_default=False,
        ),
    ]
