# Generated by Django 4.2.7 on 2024-01-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_assignmentreport_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentreport',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='assignmentreport',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='notification',
            name='isRead',
            field=models.BooleanField(verbose_name=False),
        ),
    ]
