# Generated by Django 4.2.7 on 2024-01-07 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_assignmentreport_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentreport',
            name='status',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
