# Generated by Django 4.2.7 on 2024-01-07 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_assignmentreport_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignmentreport',
            old_name='status',
            new_name='completedStatus',
        ),
    ]
